"""initial schema

Revision ID: 8a9ced53b222
Revises: 
Create Date: 2026-04-07 17:12:37.912613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9ced53b222'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lamp_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(length=5000), nullable=False),
    sa.Column('key_topics', sa.JSON(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_summaries_lamp_id_timestamp', 'conversation_summaries', ['lamp_id', 'ended_at'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_lamp_id'), 'conversation_summaries', ['lamp_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('lamp_id', sa.String(length=50), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('user_input', sa.String(length=500), nullable=True),
    sa.Column('ai_response', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_lamp_id'), 'conversations', ['lamp_id'], unique=False)
    op.create_index('ix_conversations_lamp_id_timestamp', 'conversations', ['lamp_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_conversations_timestamp'), 'conversations', ['timestamp'], unique=False)
    op.create_table('device_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('lamp_id', sa.String(length=50), nullable=False),
    sa.Column('motor_positions', sa.JSON(), nullable=False),
    sa.Column('health_status', sa.JSON(), nullable=False),
    sa.Column('light_color', sa.JSON(), nullable=False),
    sa.Column('conversation_state', sa.String(length=50), nullable=False),
    sa.Column('uptime_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_states_lamp_id'), 'device_states', ['lamp_id'], unique=False)
    op.create_index('ix_device_states_lamp_id_conversation_state', 'device_states', ['lamp_id', 'conversation_state'], unique=False)
    op.create_index('ix_device_states_lamp_id_timestamp', 'device_states', ['lamp_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_device_states_timestamp'), 'device_states', ['timestamp'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lamp_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_lamp_id'), 'memories', ['lamp_id'], unique=False)
    op.create_index('ix_memories_lamp_id_active', 'memories', ['lamp_id', 'is_active'], unique=False)
    op.create_index('ix_memories_lamp_id_category', 'memories', ['lamp_id', 'category'], unique=False)
    op.create_index('ix_memories_lamp_id_importance', 'memories', ['lamp_id', 'importance'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('lamp_id', sa.String(length=50), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_lamp_id'), 'operation_logs', ['lamp_id'], unique=False)
    op.create_index('ix_operation_logs_lamp_id_success_timestamp', 'operation_logs', ['lamp_id', 'success', 'timestamp'], unique=False)
    op.create_index('ix_operation_logs_lamp_id_timestamp', 'operation_logs', ['lamp_id', 'timestamp'], unique=False)
    op.create_index('ix_operation_logs_operation_type', 'operation_logs', ['operation_type'], unique=False)
    op.create_index('ix_operation_logs_success', 'operation_logs', ['success'], unique=False)
    op.create_index(op.f('ix_operation_logs_timestamp'), 'operation_logs', ['timestamp'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lamp_id', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('brightness_level', sa.Integer(), nullable=False),
    sa.Column('volume_level', sa.Integer(), nullable=False),
    sa.Column('deepseek_model', sa.String(length=100), nullable=True),
    sa.Column('deepseek_base_url', sa.String(length=200), nullable=True),
    sa.Column('deepseek_api_key', sa.String(length=200), nullable=True),
    sa.Column('vision_enabled', sa.Boolean(), nullable=False),
    sa.Column('modelscope_model', sa.String(length=200), nullable=True),
    sa.Column('modelscope_api_key', sa.String(length=200), nullable=True),
    sa.Column('modelscope_timeout_s', sa.Float(), nullable=False),
    sa.Column('camera_width', sa.Integer(), nullable=False),
    sa.Column('camera_height', sa.Integer(), nullable=False),
    sa.Column('camera_rotate_deg', sa.Integer(), nullable=False),
    sa.Column('camera_flip', sa.String(length=20), nullable=False),
    sa.Column('baidu_tts_per', sa.Integer(), nullable=False),
    sa.Column('led_brightness', sa.Integer(), nullable=False),
    sa.Column('lamp_port', sa.String(length=50), nullable=False),
    sa.Column('greeting_text', sa.String(length=500), nullable=True),
    sa.Column('noise_cancellation', sa.Boolean(), nullable=False),
    sa.Column('motion_cooldown_s', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_settings_updated_at', 'user_settings', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('device_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('device_secret', sa.String(length=100), nullable=False),
    sa.Column('permission_level', sa.String(length=20), nullable=False),
    sa.Column('bound_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_device_bindings_device_id'), 'device_bindings', ['device_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_device_bindings_device_id'), table_name='device_bindings')
    op.drop_table('device_bindings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_user_settings_updated_at', table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_operation_logs_timestamp'), table_name='operation_logs')
    op.drop_index('ix_operation_logs_success', table_name='operation_logs')
    op.drop_index('ix_operation_logs_operation_type', table_name='operation_logs')
    op.drop_index('ix_operation_logs_lamp_id_timestamp', table_name='operation_logs')
    op.drop_index('ix_operation_logs_lamp_id_success_timestamp', table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_lamp_id'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index('ix_memories_lamp_id_importance', table_name='memories')
    op.drop_index('ix_memories_lamp_id_category', table_name='memories')
    op.drop_index('ix_memories_lamp_id_active', table_name='memories')
    op.drop_index(op.f('ix_memories_lamp_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_device_states_timestamp'), table_name='device_states')
    op.drop_index('ix_device_states_lamp_id_timestamp', table_name='device_states')
    op.drop_index('ix_device_states_lamp_id_conversation_state', table_name='device_states')
    op.drop_index(op.f('ix_device_states_lamp_id'), table_name='device_states')
    op.drop_table('device_states')
    op.drop_index(op.f('ix_conversations_timestamp'), table_name='conversations')
    op.drop_index('ix_conversations_lamp_id_timestamp', table_name='conversations')
    op.drop_index(op.f('ix_conversations_lamp_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_conversation_summaries_lamp_id'), table_name='conversation_summaries')
    op.drop_index('ix_conv_summaries_lamp_id_timestamp', table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
