/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountSettings: typeof import('./src/components/settings/AccountSettings.vue')['default']
    BehaviorConfig: typeof import('./src/components/settings/BehaviorConfig.vue')['default']
    CameraConfig: typeof import('./src/components/settings/CameraConfig.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    HardwareConfig: typeof import('./src/components/settings/HardwareConfig.vue')['default']
    LightPanel: typeof import('./src/components/room/LightPanel.vue')['default']
    LLMConfig: typeof import('./src/components/settings/LLMConfig.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    PrivacyIndicator: typeof import('./src/components/common/PrivacyIndicator.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeechConfig: typeof import('./src/components/settings/SpeechConfig.vue')['default']
    StatusIndicator: typeof import('./src/components/common/StatusIndicator.vue')['default']
    UIConfig: typeof import('./src/components/settings/UIConfig.vue')['default']
    VisionConfig: typeof import('./src/components/settings/VisionConfig.vue')['default']
    WiFiSettings: typeof import('./src/components/settings/WiFiSettings.vue')['default']
  }
}
